name: PR From Query Engine

on:
  repository_dispatch:
    types: [sync-query-engine]
  workflow_dispatch:       

jobs:
  push-subtrees:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fullstack
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.QUERY_ENGINE_KEY }}

      - name: Set Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set branch name from payload
        run: echo "BRANCH_NAME=${{ github.event.client_payload.branch }}" >> $GITHUB_ENV

      - name: Add query-engine remote
        run: git remote add qe-remote git@github.com:OPSILab/query-engine.git || echo "Remote already exists"

      - name: Pull latest from subtree
        run: git subtree pull --prefix=Query-Engine qe-remote ${{ env.BRANCH_NAME }} --squash || echo "No changes to pull"

      #- name: Exit if last commit is from bot
      #  run: |
      #    LAST_AUTHOR=$(git log -1 --pretty=format:'%an' -- Query-Engine)
      #    if [[ "$LAST_AUTHOR" == "github-actions[bot]" ]]; then
      #      echo "Last commit touching Query-Engine was made by bot, exiting."
      #      exit 0
      #    fi

      - name: Push branch / create branch if needed
        run: |          
          if git ls-remote --heads origin ${{ env.BRANCH_NAME }} | grep -q ${{ env.BRANCH_NAME }}; then
            echo "Branch exists on remote, pushing subtree..."
            git push origin ${{ env.BRANCH_NAME }}
          else
            echo "Branch does not exist on remote, creating branch..."
            git push origin HEAD:refs/heads/${{ env.BRANCH_NAME }}
          fi
          
